### ISSUE TITLE
Part 3 (Part 3 dev) solution is missing projects

### ISSUE THREAD

**Issue by BenHayat** [JonPSmith/EfCoreinAction-SecondEdition#3]
Hi Jon;

I just download the three parts. But in part 3 the solution is missing a series of projects. Could you please investigate?
Thanks!

**Comment by JonPSmith** [comment]
Hi @BenHayat,

I did make some changes in the last week or two, but everything should be there. Can you do a Git Pull to check you have the latest. I did a tiny comment update push this morning - is ID is d334c4a

**Comment by BenHayat** [comment]
I basically downloaded all the solutions, but solution part 3, is missing a few projects.
Just download it, unzip and try to build it. You should be able to replicate it.

**Comment by JonPSmith** [comment]
I looked at the repo in GitHub and it has all the projects I have in my code. 

What projects are you missing?

**Comment by BenHayat** [comment]
The reason VS couldn't load/find them was due to long name including the folder names that exceeded the limit. I just shortened the folder names and it loaded.

C:\Manning Publications\EF In Action eBook\Second Edition\Code Samples\Github source\Part 3\EfCoreinAction-SecondEdition-Part3

**Comment by JonPSmith** [comment]
I would strongly recommend cloning the https://github.com/JonPSmith/EfCoreinAction-SecondEdition repo and not using the Manning download. I asked Manning to remove that, but they don't want to do that.

I keep https://github.com/JonPSmith/EfCoreinAction-SecondEdition up to date at all times.

**Comment by BenHayat** [comment]
Thanks for the notification. I will go ahead and remove the Manning download.
