### ISSUE TITLE
Where do I leave review on Manning site?

### ISSUE THREAD

**Issue by BenHayat** [JonPSmith/EfCoreinAction-SecondEdition#5]
Hi Jon;

I'm enjoying your well written book and would like to share my opinion with others via the customer review. However, I can't find any link (even when I'm logged in) in Manning site to give review and vote. I've sent them an email but no response.

Do you know the link?

https://www.manning.com/books/entity-framework-core-in-action-second-edition?query=ef#reviews

**Comment by jtreher** [comment]
I don't think you can leave a review on Manning.com unless you are a certified reviewer. I wanted to leave a review regarding Code like a Pro in C# and hit a dead end like you.

**Comment by JonPSmith** [comment]
Hi @BenHayat and @jtreher,

Sorry to @BenHayat for not replying to your question. I was really busy around that time getting the book proofed and printed.

I'm not sure how the Manning's site works, but @jtreher's comment suggests review are controlled. Bit weird, but maybe they have problems with spammers.
