### ISSUE TITLE
Don't you mean 5.0.1?

### ISSUE THREAD

**Issue by BenHayat** [JonPSmith/EfCoreinAction-SecondEdition#6]
Hi Jon;

Don't you EF 5.0.1 Update comments than 5.1?
Screen shot is attached.

![5 01](https://user-images.githubusercontent.com/7861196/108782571-cdb97080-7539-11eb-96a0-26203116e809.png)

**Comment by JonPSmith** [comment]
Yep. Should be 5.0.1
